version: '3'  #Задаем версию docker-compose.yml
services: #Задаем контейнеры
  flask: #Задаем название контейнера и настраиваем его
    # Путь до Dockerfile
    build: ./flask
    # Имя для создаваемого контейнера
    container_name: server-flask
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся в  директории /flask/app, появятся в директории контейнера /app
    volumes:
      - ./flask/app:/app
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    command: python server.py
  
  php: #Задаем название второго контейнера и настраиваем его
    # Путь до Dockerfile
    build: ./php_apache
    # Имя для создаваемого контейнера
    container_name: server-php
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    volumes:
      - ./php_apache/app:/var/www/html
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5001:5001"
    